### ISSUE TITLE
構築時メモ

### ISSUE THREAD

**Issue by ave-hikari** [ave-hikari/practice-rails-coach#1]
rbenv で2.6.1がリストされない
```
$ cd /Users/Hikari/.rbenv/plugins/ruby-build && git pull && cd -
```

**Comment by ave-hikari** [comment]
sqlite3 入れとくこと
```
$ rails g scaffold book                                                                                                            [12:48:51]
/Users/Hikari/.rbenv/versions/2.6.1/lib/ruby/2.6.0/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem': Error loading the 'sqlite3' Active Record adapter. Missing a gem it depends on? can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile. (LoadError)
	from /Users/Hikari/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/activerecord-5.2.2/lib/active_record/connection_adapters/sqlite3_adapter.rb:12:in `<main>'
	from /Users/Hikari/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `require'
	from /Users/Hikari/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:21:in `block in require_with_bootsnap_lfi'
	from /Users/Hikari/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/loaded_features_index.rb:83:in `register'
	from /Users/Hikari/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/bootsnap-1.4.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:20:in `require_with_bootsnap_lfi'
```
→ `gem 'sqlite3', '~> 1.3.6'` 記載、bundle install して再実行
